### ISSUE TITLE
where条件是数组，只有第一个条件生效，其余条件不生效

### ISSUE THREAD

**Issue by yxyAlex** [Lany-w/mingdaoyun-php-sdk#2]
![496092b06c10e8e3a0985d4af9b3bb8](https://user-images.githubusercontent.com/50318887/222322165-0cffd9c9-5e0a-4c13-a90c-a0b0712a82de.png)

用版本是1.4.0，1.2.0版本是正常的

**Comment by Lany-w** [comment]
已经修复了,可以更新到1.4.1使用
