### ISSUE TITLE
条件查询用all的查询多次，第二次会将第一次的条件累加进去

### ISSUE THREAD

**Issue by yxyAlex** [Lany-w/mingdaoyun-php-sdk#3]
![allbug1](https://user-images.githubusercontent.com/50318887/223317498-1709e5c2-ebd6-45b4-b628-59dbe8ca9334.png)
![allbug2](https://user-images.githubusercontent.com/50318887/223317507-2517a390-363a-4fc5-af21-bc58c4d12fe0.png)

**Comment by yxyAlex** [comment]
@Lany-w

**Comment by Lany-w** [comment]
@yxyAlex 感谢指出,1.4.3已修改
